spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:user_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}

auth:
    jwtSecret: fsyfashvagsuygsqagjhabsmbqw231t67512736teuqbk32t3781
    jwtExpirationMs: 300