apiVersion: v1
kind: Service
metadata:
    name: easy-recipes-service
    labels:
        app: easy-recipes
spec:
    type: LoadBalancer
    selector:
        app: easy-recipes
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
