spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:password}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:stocks_db}?authSource=admin
server:
  port: 8100

#logging:
#  config: classpath:logback-spring.xml



#  elasticsearch:
#      rest:
#        uris: http://localhost:9200

  application:
    name: stock-service
#  config:
#    import: configserver:http://localhost:8188


