spring:
  data:
    mongodb:
      username: admin
      password: password
      host: localhost
      database: stocks_db
      port: 27017
server:
  port: 8100

#logging:
#  config: classpath:logback-spring.xml



  elasticsearch:
      rest:
        uris: http://localhost:9200

  application:
    name: stock-service
  config:
    import: configserver:http://localhost:8188


