networks:
  app-network:

volumes:
  mysql-data:

services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product_db
#    ports:
#      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  product-app:
    image: product-app:latest
    container_name: product-app
    ports:
      - "5000:8080"
    depends_on:
      - mysql-container
    environment:
      MYSQL_HOST: mysql-container
      MYSQL_PORT: 3306
      MYSQL_DB: product_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password