spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:product_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true


#  profiles:
#    active: ${ACTIVE_PROFILE:dev}
#
#  liquibase:
#    change-log: classpath:/db/changelog/db.changelog-master.xml