spring:
  kafka:
    bootstrap-servers: localhost:30092
    consumer:
      group-id: my-order-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer