apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ram1uj/auth-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_DATABASE
              value: "user_db"
            - name: MYSQL_PORT
              value: "3306"
          imagePullPolicy: Always