apiVersion: v1
kind: Service
metadata:
    name: portfolio-service
spec:
    selector:
        app: portfolio-service
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
          nodePort: 30002
    type: NodePort