apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-service
  template:
    metadata:
      labels:
        app: portfolio-service
    spec:
      containers:
        - name: portfolio-service
          image: ram1uj/portfolio-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USER
              value: "root"
            - name: MONGO_PASSWORD
              value: "password"
            - name: MONGO_HOST
              value: "mongodb"
            - name: MONGO_DATABASE
              value: "stocks_db"
            - name: MONGO_PORT
              value: "27017"
          imagePullPolicy: Always