apiVersion: v1
kind: Service
metadata:
    name: stocks-service
spec:
    selector:
        app: stocks-service
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
          nodePort: 30001
    type: NodePort