apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stocks-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stocks-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
         name: requests_per_second
         target:
           type: AverageValue
           averageValue: "100"