spring:
  datasource:
    url: jdbc:h2:mem:product_db
    username: sa
    password: password
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true


